Grab papers?

In [1]:
import dimcli
from dimcli.utils import *
from API_keys.DIMCLI_APIKEY import API_KEY
import json
import sys
import pandas as pd

print("==\nLogging in..")
# https://digital-science.github.io/dimcli/getting-started.html#authentication
ENDPOINT = "https://app.dimensions.ai"
dimcli.login(key=API_KEY, endpoint=ENDPOINT)
dsl = dimcli.Dsl()

Login failed: please ensure your credentials are correct.

==
Logging in..

HTTPError: 401 Client Error: Unauthorized for url: https://app.dimensions.ai/api/auth.json

Search by "concept"

In [3]:
q = """search publications for "superconduct*"
            where year>1970
       return publications[id+doi+title+year+journal+times_cited] limit 100"""
results = dsl.query(q) 
results.as_dataframe()

Returned Publications: 100 (total = 1241372)
Time: 0.77s

,id,title,doi,times_cited,year,journal.id,journal.title
0,pub.1194816109,Topological Surface Superconductivity via Jose...,10.1021/acs.nanolett.5c04230,0,2025,jour.1028316,Nano Letters
1,pub.1194815738,Modulation of Electronic Liquid-Crystal Phases...,10.1021/acs.nanolett.5c04560,0,2025,jour.1028316,Nano Letters
2,pub.1194777976,Manipulating Spin States by Metal Axial Coordi...,10.1002/advs.202517166,0,2025,jour.1052235,Advanced Science
3,pub.1194776854,Maximal Rashba Splitting in GeTe/Bi2Te3 Hetero...,10.1002/advs.202513673,0,2025,jour.1052235,Advanced Science
4,pub.1194776082,Realization of Room-Temperature Ferromagnetic ...,10.1021/acsami.5c17318,0,2025,jour.1041450,ACS Applied Materials & Interfaces
...,...,...,...,...,...,...,...
95,pub.1194582910,Measurement-device-independent continuous vari...,10.1038/s41377-025-02039-x,0,2025,jour.1048610,Light: Science & Applications
96,pub.1194571669,Impact of Electrolyte Temperature on Solution‐...,10.1002/open.202500137,0,2025,jour.1047592,ChemistryOpen
97,pub.1194548460,Accurate Chemical Reaction Modeling on a Noisy...,10.1021/acs.jpclett.5c02770,0,2025,jour.1043112,The Journal of Physical Chemistry Letters
98,pub.1194545951,One‐Dimensional Hydrogen Chains in Li–Hf–H Sys...,10.1002/advs.202514126,0,2025,jour.1052235,Advanced Science
99,pub.1194544426,New magnetic topological materials from high-t...,10.1126/sciadv.adv8780,0,2025,jour.1051517,Science Advances

In [4]:
q = """search publications in authors for "Weiliang Luo"
       return publications[id+doi+title+year+journal+times_cited] limit 100"""
results = dsl.query(q) 
results.as_dataframe()

Returned Publications: 37 (total = 37)
Time: 5.88s

,id,title,doi,times_cited,year,journal.id,journal.title
0,pub.1187403127,Bridging machine learning and thermodynamics f...,10.1021/scimeetings.5c11156,0,2025,NaN,NaN
1,pub.1181619305,Music102: An $D_{12}$-equivariant transformer ...,10.48550/arxiv.2410.18151,0,2025,jour.1371339,arXiv
2,pub.1123868290,A question on Chinese guidelines for the diagn...,10.3760/cma.j.issn.1006-7876.2019.08.015,0,2019,jour.1116231,Chinese Journal of Neurology
3,pub.1094255285,Research on Quality Evaluation of Multimedia C...,10.1109/iita.2009.220,0,2009,NaN,NaN
4,pub.1030513070,Hospitalization expenses of acute ischemic str...,10.1080/13696998.2016.1229322,6,2016,jour.1103761,Journal of Medical Economics
5,pub.1060742381,L-hop percolation on networks with arbitrary d...,10.1103/physreve.84.031113,24,2011,jour.1312290,Physical Review E
6,pub.1024376389,Real-time detection and prevention of android ...,10.1145/2484417.2484422,9,2013,NaN,NaN
7,pub.1189945077,Duan Guochao's Academic Interactions in the Fi...,10.30560/hssr.v8n3p132,0,2025,jour.1321330,Humanities and Social Science Research
8,pub.1157363705,Autoimmune glial fibrillary acidic protein ast...,10.1007/s13760-023-02268-0,14,2023,jour.1312027,Acta Neurologica Belgica
9,pub.1140435978,Trajectories of posttraumatic growth in young ...,10.21037/apm-21-1879,13,2021,jour.1046975,Annals of Palliative Medicine
10,pub.1018485842,Key-insulated symmetric key cryptography and m...,10.1145/2414456.2414489,18,2012,NaN,NaN
11,pub.1188263731,The Mental Health Implications of People‐Pleas...,10.1002/pchj.70016,1,2025,jour.1047834,PsyCh Journal
12,pub.1142375470,Clinical characteristics and outcomes of wake-...,10.3760/cma.j.issn.1673-4165.2021.04.001,1,2021,jour.1393127,International Journal of Cerebrovascular Diseases
13,pub.1093986123,Design a Low Power Wireless Fire Detector Base...,10.1109/icicta.2010.395,2,2010,NaN,NaN
14,pub.1044665876,Federated Cloud Security Architecture for Secu...,10.1007/978-1-4614-3296-8_7,11,2013,NaN,NaN
15,pub.1044342006,CO2 absorption using biphasic solvent: Blends ...,10.1016/j.ijggc.2016.07.036,95,2016,jour.1137796,International Journal of Greenhouse Gas Control
16,pub.1094385465,Benchmarking Joyent SmartDataCenter for Hadoop...,10.1109/ccem.2013.6684429,0,2013,NaN,NaN
17,pub.1182083795,Effect of posterior-stabilized and cruciate-re...,10.52312/jdrs.2024.1836,0,2024,jour.1429572,Joint Diseases and Related Surgery
18,pub.1173723121,Comparison of the Clinical Outcomes Between Re...,10.2147/cia.s464010,1,2024,jour.1036808,Clinical Interventions in Aging
19,pub.1168098287,A rare case of anti-DPPX encephalitis combined...,10.1186/s12883-024-03538-x,5,2024,jour.1024950,BMC Neurology
20,pub.1134399868,Effects of the COVID-19 pandemic on reperfusio...,10.1007/s10072-020-04938-w,8,2021,jour.1294956,Neurological Sciences
21,pub.1085765737,Evaluation and Modeling of Vapor–Liquid Equili...,10.1021/acs.est.7b00379,26,2017,jour.1012116,Environmental Science and Technology
22,pub.1001115272,Empirical research on construction of a measur...,10.1080/10042857.2015.1033806,19,2015,jour.1140065,Chinese Journal of Population Resources and En...
23,pub.1095686573,Building Malware Infection Trees,10.1109/malware.2011.6112326,5,2011,NaN,NaN
24,pub.1165209561,Chinese stroke patients with atrial fibrillati...,10.1038/s41598-023-45379-7,1,2023,jour.1045337,Scientific Reports
25,pub.1163629579,Uni-pKa: An Accurate and Physically Consistent...,10.26434/chemrxiv-2023-lw5k0,1,2023,jour.1315496,ChemRxiv
26,pub.1138871748,Clinical Characteristics and Outcomes of Acute...,10.1155/2021/5517228,4,2021,jour.1042219,International Journal of Endocrinology
27,pub.1032554747,Systematic study of aqueous monoethanolamine‐b...,10.1002/ese3.101,229,2015,jour.1146511,Energy Science & Engineering
28,pub.1025140633,CO2 absorption into aqueous amine blended solu...,10.1016/j.ces.2014.12.053,149,2015,jour.1127662,Chemical Engineering Science
29,pub.1173902316,Bridging Machine Learning and Thermodynamics f...,10.1021/jacsau.4c00271,19,2024,jour.1399870,JACS Au
30,pub.1165040258,Uni-pKa: An Accurate and Physically Consistent...,10.21203/rs.3.rs-3367941/v1,0,2023,jour.1380788,Research Square
31,pub.1107211071,"Diagnostic accuracy of STAF, LADS, and iPAB sc...",10.1002/clc.23080,11,2018,jour.1089335,Clinical Cardiology
32,pub.1075112511,[Polymorphisms of ACE-1 and MTHFR genes and ge...,NaN,19,2002,jour.1297345,National Medical Journal of China
33,pub.1190576662,Regularized Second-Order Møller–Plesset Theory...,10.1021/acs.jctc.5c00534,2,2025,jour.1034502,Journal of Chemical Theory and Computation
34,pub.1191213817,Enhancing Materials Discovery with Valence Con...,10.48550/arxiv.2507.19799,0,2025,jour.1371339,arXiv
35,pub.1193595094,Exploring beyond experiment: generating high-q...,10.1016/j.coche.2025.101189,1,2025,jour.1047329,Current Opinion in Chemical Engineering
36,pub.1145199593,Combined Approach to Eptifibatide and Thrombec...,10.1161/strokeaha.121.036754,28,2022,jour.1013101,Stroke